### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by librarychik**
Update wiki documentation text

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by bryjbrown** [comment]
@librarychik Just wondering what the context is for this change? The line `Further documentation for this module is available at [our wiki]` is pretty standard across all the READMEs, see the following examples:
- [Islandora](https://github.com/Islandora/islandora/blob/7.x/README.md#documentation)
- [Islandora Scholar](https://github.com/islandora/islandora_scholar#documentation)
- [Islandora Usage Stats](https://github.com/Islandora/islandora_usage_stats#documentation)

**Comment by DonRichards** [comment]
@bryjbrown it was discussed during documentation interest group call and on the last release call. After committers call I put together an email to all those who signed up for documentation. The differentiation between those with additional information on the wiki verse those with the same info should be indicated.

**Comment by bryjbrown** [comment]
@DonRichards My bad, didn't know about that. Apologies @librarychik!

**Comment by librarychik** [comment]
@bryjbrown no worries.  :smile_cat:  @DonRichards maybe we should send out a general notice about this? I think most Read Me's will need to be updated to the new wording.

**Comment by DonRichards** [comment]
@librarychik Not a bad idea. I don't mind throwing something onto Google groups.

**Review by DonRichards — APPROVED** [review]
Thanks

**Pull request merged**
